name: Export VGGT to ONNX

on:
  push:
    branches:
      - main

jobs:
  export:
    name: Export
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Python dependencies
        run: pip install -r vggt/requirements.txt
      - name: Export ONNX file
        run: |
          pip install onnx
          mkdir vggt-onnx
          PYTHONPATH=vggt python export_vggt.py
      - name: Merge ONNX weights into single file
        run: python merge_onnx.py
      - name: Test ONNX export
        run: |
          pip install onnxruntime
          PYTHONPATH=vggt python test_onnx.py
      - name: Configure Git
        run: |
          git config --global user.name "Adrian Kretz"
          git config --global user.email "me@akretz.com"
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          huggingface-cli login --token $HF_TOKEN
          git lfs install
          git clone https://huggingface.co/akretz/VGGT-1B-onnx
          mv vggt.onnx* VGGT-1B-onnx
          cd VGGT-1B-onnx
          git add vggt.onnx*
          git commit -m "Update model via GitHub Actions"
          git push
