name: Export VGGT to ONNX

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  export:
    name: Export
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Python dependencies
        run: pip install -r vggt/requirements.txt
      - name: Export ONNX file
        run: |
          pip install onnx
          mkdir onnx{,_fp16}
          PYTHONPATH=vggt python export_vggt.py
      - name: Merge ONNX weights into single file
        run: python merge_onnx.py
      - name: Test ONNX export
        run: |
          pip install onnxruntime
          PYTHONPATH=vggt python test_onnx.py
      - name: Free some disk space
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
      - name: Push to Hugging Face
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git clone https://akretz:${{ secrets.HF_TOKEN }}@huggingface.co/akretz/VGGT-1B-onnx
          mv vggt.onnx* VGGT-1B-onnx
          cd VGGT-1B-onnx
          git config user.name "Adrian Kretz"
          git config user.email "me@akretz.com"
          git add vggt.onnx*
          git commit -m "Update model via GitHub Actions"
          git push
